---
output:
  html_document:
        theme: null
        mathjax: null
        citation_package: biblatex
params:
    norma: null
    referencias: null
bibliography: biblatexExamples.bib
csl: styles/`r params$norma`
lang: pt
suppress-bibliography: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval=TRUE, message=FALSE, warning=FALSE)
```


```{r library}
library(htmltools)
```

```{r apa7}
# APA7 formato ------------------------------------------------------------

# Artigo de periódico
apa7norms <- if (params$referencias %in% c("CitekeyArticle")) {
    p("Autor, A. A. (ano). Título do artigo.", em("Título do periódico, "), em("volume", .noWS="outside"),"(número), páginas inicial–final do artigo. https://doi.org/xxxx")
    # 21+ Autores
} else if (params$referencias == "CitekeyArticle2") {
    p("Autor, A. A., Autor, B. B. (ano). Título do artigo", em("Título do periódico, "), em("volume", .noWS="outside"),"(número), páginas inicial–final do artigo. https://doi.org/xxxx") 
    # Autor institucional
} else if (params$referencias == "CitekeyArticle3") {
    p("Autor, A. A., Autor, B. B., Autor, C. C. (ano). Título do artigo", em("Título do periódico, "), em("volume", .noWS="outside"),"(número), páginas inicial–final do artigo. https://doi.org/xxxx") 
    # Autor institucional
} else if (params$referencias == "CitekeyArticle4") {
    p("Autor, A. A., Autor, B. B., Autor, C. C., Autor, D. D. (ano). Título do artigo", em("Título do periódico, "), em("volume", .noWS="outside"),"(número), páginas inicial–final do artigo. https://doi.org/xxxx") 
    # Autor institucional
} else if (params$referencias == "CitekeyArticle7") {
    p("Autor, A. A., Autor, B. B., Autor, C. C., Autor, D. D., Autor, E. E., Autor, F. F., Autor, G. G. (ano). Título do artigo", em("Título do periódico, "), em("volume", .noWS="outside"),"(número), páginas inicial–final do artigo. https://doi.org/xxxx") 
    # Autor institucional
} else if (params$referencias == "CitekeyArticle21") {
    p("Autor, A. A., Autor, B. B., Autor, C. C., Autor, D. D., Autor, E. E., Autor, F. F., Autor, G. G., Autor, H. H., Autor, I. I., Autor, J. J., Autor, K. K., Autor, L. L., Autor, M. M., Autor, N. N., Autor, O. O., Autor, P. P., Autor, Q. Q., Autor, R. R., Autor, S. S., … Autor, V. V. (ano). Título do artigo", em("Título do periódico, "), em("volume", .noWS="outside"),"(número), páginas inicial–final do artigo. https://doi.org/xxxx") 
    # Autor institucional
} else if (params$referencias == "CitekeyGroupBook") {
    p("Nome do grupo. (ano).", em("Título do livro"), "(N.ª ed, Vol. M) [se houver].", "Nome da editora.")
    # Livro
} else if (params$referencias == "CitekeyBook") {
    p("Autor, A. A. (ano).", em("Título do livro"), "(N.ª ed., Vol. M) [se houver].", "Nome da editora.", "https://doi.org/xxxx [se houver]")
    # Capítulo de livro
} else if (params$referencias == "CitekeyInbook") {
    p("Autor, A. A. (ano).", "Título do capítulo.", "Em E. E. Editor & F. F. Editor (Eds.),", em("Título do livro"), "(N.ª ed., Vol. M [se houver], pp. inicial--final).", "Nome da editora. https://doi.org/xxxxx [se houver]")
    # Trabalho apresentado em congresso
} else if (params$referencias == "CitekeyInproceedings") {
    p("Apresentador, A. A., & Apresentador, B. B. (Ano, Mês dia inicial–dia final).", em("Título da contribuição"), "[Tipo da contribuição].", "Nome do congresso, Localização.", "DOI (https://doi.org/xxxx) ou URL (https://xxxx)")
    # Dissertação de mestrado
} else if (params$referencias == "CitekeyMastersthesis") {
    p("Autor, A. A. (ano).", em("Título da dissertação"), "[Dissertação de mestrado, Nome da Instituição].", "Repositório. https://xxxx")
    # Tese de doutorado
} else if (params$referencias == "amaral15") {
    p("Autor, A. A. (ano).", em("Título da tese"), "[Tese de doutorado, Nome da Instituição].", "Repositório. https://xxxx")
    # Livro publicado por editores
} else if (params$referencias == "CitekeyProceedings") {
    p("Editor, E. E., & Editor, F. F. (Eds.). (ano).", em("Título do livro"), "(N.ª ed., Vol. M) [se houver].", "Nome da editora.", "https://doi.org/xxxxx [se houver]")
    # Trabalho não publicado
} else if (params$referencias == "CitekeyUnpublished") {
    p("Autor, A. A. & Autor, B. B. (ano).", em("Título do trabalho"), "[Manuscrito não publicado/ Manuscrito em preparação/ Manuscrito submetido para publicação].", "Fonte do trabalho (e.g., Nome do departamento, Nome da universidade).", "https://xxxx [se houver]")
    # Blog, revista ou jornal online
} else if (params$referencias == "blogpost") {
    p("Autor, A. A. & Autor, B. B.", strong("ou"), "Nome do Grupo/Instituição.", "(ano, mês dia [se houver]).", em("Título do trabalho."), "Nome do site.", "Recuperado em Mês dia, ano [apenas se o conteúdo não for uma página estática ou arquivada], de https://xxxxx")
    # Testes, escalas e inventários
} else if (params$referencias == "testes") {
    p("Autor, A. A. & Autor, B. B.", "(ano).", em("Título do teste."), "https://xxxxx")
}


# APA7 exemplos ----------------------------------------------------------

apa7ex <- if (params$referencias == "CitekeyArticle") {
    p("Borsboom, D. (2006). The Attack of the Psychometricians.", em("Psychometrika, "), em("71", .noWS="outside"),"(3), 425–440. https://doi.org/10.1007/s11336-006-1447-6")
    # 2 Autores
} else if (params$referencias == "CitekeyArticle2") {
    p("Kashdan, T. B., & Rottenberg, J. (2010). Psychological flexibility as a fundamental aspect of health.", em("Psychology Review, "), em("30", .noWS="outside"),"(7), 865–878. https://doi.org/10.1016/j.cpr.2010.03.001")
    # 3 autores
} else if  (params$referencias == "CitekeyArticle3") {
    p("Wijsen, L. D., Borsboom, D., & Alexandrova, A. (2022). Values in Psychometrics.", em("Perspectives on Psychological Science, "), em("17", .noWS="outside"),"(3), 788–804. https://doi.org/10.1177/17456916211014183")
    # 4+ autores
} else if (params$referencias == "CitekeyArticle4") {
    p("Blanken, T. F., Borsboom, D., Penninx, B. W., & Van Someren, E. J. (2020). Network Outcome Analysis Identifies Difficulty Initiating Sleep as a Primary Target for Prevention of Depression: A 6-Year Prospective Study.", em("Sleep, "), em("45", .noWS="outside"),"(5), 1–6. https://doi.org/10.1093/sleep/zsz288")
    # 7+
} else if (params$referencias == "CitekeyArticle7") {
    p("Baglioni, C., Battagliese, G., Feige, B., Spiegelhalder, K., Nissen, C., Voderholzer, U., Lombardo, C., & Riemann, D. (2011). Insomnia as a Predictor of Depression: A Meta-Analytic Evaluation of Longitudinal Epidemiological Studies", em("Journal of Affective Disorders, "), em("135", .noWS="outside"),"(1), 10–19. https://doi.org/10.1016/j.jad.2011.01.011")
    # 21+ autores
} else if (params$referencias == "CitekeyArticle21") {
    p("Page, M. J., McKenzie, J. E., Bossuyt, P. M., Boutron, I., Hoffmann, T. C., Mulrow, C. D., Shamseer, L., Tetzlaff, J. M., Akl, E. A., Brennan, S. E., Chou, R., Glanville, J., Grimshaw, J. M., Hróbjartsson, A., Lalu, M. M., Li, T., Loder, E. W., Mayo-Wilson, E., McDonald, S., … Moher, D. (2021). The PRISMA 2020 Statement: An Updated Guideline for Reporting Systematic Reviews.", em("BMJ, "), em("372."),"https://doi.org/10.1136/bmj.n71")
    # Livro
    # Autor institucional
} else if (params$referencias == "CitekeyGroupBook") {
    p("American Psychiatric Association. (2014).", em("Manual Diagnóstico e Estatístico de Transtornos Mentais"), "(5.ª ed).", "Artmed.")
    # Livro
} else if (params$referencias == "CitekeyBook") {
    p("Susskind, L., & Hrabovsky, G. (2014).", em("Classical mechanics: the theoretical minimum."), "Penguin Random House.")
    # Capítulo de livro
} else if (params$referencias == "CitekeyInbook") {
    p("Balsam, K. F., Martell, C. R., Jones, K. P., & Safren, S. A. (2019).", "Affirmative cognitive behavior therapy with sexual and gender minority people.", "Em G. Y. Iwamasa & P. A. Hays (Eds.),", em("Culturally responsive cognitive behavior therapy: Practice and supervision"), "(2.ª ed., pp. 7–13).", "American Psychological Association. https://doi.org/10.1037/0000119-012")
    # Trabalho apresentado em congresso
} else if (params$referencias == "CitekeyInproceedings") {
    p("Pearson, J. (2018, Setembro 27–30).", em("Fat talk and its effects on state-based body image in women"), "[Apresentação de Pôster].", "Australian Psychological Society Congress, Sydney, NSW, Australia.", "http://bit.ly/2XGSThP")
    # Dissertação de mestrado
} else if (params$referencias == "CitekeyMastersthesis") {
    p("Rodrigues A. L. A. (2009).", em("Impacto de um programa de exercícios no local de trabalho sobre o nível de atividade física e o estágio de prontidão para a mudança de comportamento"), "[Dissertação de mestrado, Faculdade de Medicina, Universidade de São Paulo].", "Biblioteca Digital de Teses e Dissertações da USP. https://www.teses.usp.br/teses/disponiveis/5/5160/tde-24092009-161713/publico/AnaLuciaAquilasRodrigues.pdf")
    # Tese de doutorado
} else if (params$referencias == "amaral15") {
    p("Amaral, L. L. (2015).", em("A alternância transitivo-intransitiva no português brasileiro"), "[Tese de doutorado, Universidade Federal de Minas Gerais]. Repositório Institucional da Universidade Federal de Minas Gerais. http://hdl.handle.net/1843/MGSS-9VNMNV")
    # Livro publicado por editores
} else if (params$referencias == "CitekeyProceedings") {
    p("Damásio, B. F., & Borsa, J. C. (Eds.). (2018).", em("Manual de desenvolvimento de instrumentos psicológicos."), "Vetor.")
    # Trabalho não publicado
} else if (params$referencias == "CitekeyUnpublished") {
    p("Yoo, J., Miyamoto, Y., Rigotti, A., & Ryff, C. (2016).", em("Linking positive affect to blood lipids: A cultural perspective"), "[Manuscrito não publicado].", "Department of Psychology, University of Wisconsin–Madison.")
    # Blog, revista ou jornal online
} else if (params$referencias == "blogpost") {
    p("Khan, I. (2020, Fevereiro 17).", em("Why Animal Crossing Is the Game for the Coronavirus Moment."), "The New York Times.", "https://www.nytimes.com/2020/04/07/arts/animal-crossing-covid-coronavirus-popularity-millennials.html")
    # Testes, escalas e inventários
} else if (params$referencias == "testes") {
    p("Project Implicit. (n.d.).", em("Gender–Science IAT."), "https://implicit.harvard.edu/implicit/takeatest.html")
}
```

```{r abnt}
# ABNT formato ------------------------------------------------------------

# Artigo de periódico
abntnorms <- if (params$referencias %in% c("CitekeyArticle")) {
    p("AUTOR, A. A.  Título do artigo. ", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), v. X, n. Y, p. páginas inicial–final do artigo, data.")
} else if (params$referencias == "CitekeyArticle2") {
    p("AUTOR, A. A.; AUTOR, B. B.  Título do artigo. ", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), v. X, n. Y, p. páginas inicial–final do artigo, data.")
} else if (params$referencias == "CitekeyArticle3") {
    p("AUTOR, A. A.; AUTOR, B. B.; AUTOR, C. C.  Título do artigo. ", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), v. X, n. Y, p. páginas inicial–final do artigo, data.")
} else if (params$referencias == "CitekeyArticle4") {
    p("AUTOR, A. A.", em("et al."), "Título do artigo.", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), v. X, n. Y, p. páginas inicial–final do artigo, data.")
} else if (params$referencias == "CitekeyArticle7") {
    p("AUTOR, A. A.", em("et al."), "Título do artigo.", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), v. X, n. Y, p. páginas inicial–final do artigo, data.")
    # 21+ Autores
} else if (params$referencias %in% c("CitekeyArticle21")) {
    p("AUTOR, A. A.", em("et al."), "Título do artigo.", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), v. X, n. Y, p. páginas inicial–final do artigo, data.") 
    # Autor institucional
} else if (params$referencias == "CitekeyGroupBook") {
    p("NOME DO GRUPO. ", strong("Título do livro", .noWS="outside"), ". N. ed. [não indicar 1ª edição]", "Cidade: Nome da editora, ano. ISBN XX-XXXX-XXX-X [elemento complementar].")
    # Livro
} else if (params$referencias == "CitekeyBook") {
    p("AUTOR, A. A. ", strong("Título do livro", .noWS="outside"), ". N. ed. [não indicar 1ª edição]", "Cidade: Nome da editora, ano. ISBN XX-XXXX-XXX-X [elemento complementar].")
    # Capítulo de livro
} else if (params$referencias == "CitekeyInbook") {
    p("AUTOR, A. A. Título do capítulo. ", em("In", .noWS="outside"), ":", "EDITOR, E. E. (ed./coord./org.). " , strong("Título do livro", .noWS="outside"), ". N. ed. [não indicar 1ª edição]", "Cidade: Nome da editora, ano. p. páginas inicial–final do capítulo. ISBN XX-XXXX-XXX-X [elemento complementar].")
    # Trabalho apresentado em congresso
} else if (params$referencias == "CitekeyInproceedings") {
    p("AUTOR, A. A.; AUTOR, B. B. Título do trabalho. ", em("In", .noWS="outside"), " NOME DO EVENTO. numeração do evento [se houver]. ano, local (cidade) de realização. ", strong("Título do documento", .noWS="outside"), ". Local de publicação (cidade): Editora, ano. p. páginas inicial–final do artigo. Informação de disponibilidade em meio eletrônico. [se houver]")
    # Dissertação de mestrado
} else if (params$referencias == "CitekeyMastersthesis") {
    p("SOBRENOME, Nome. ", strong("Título do trabalho", .noWS="outside"), ": subtítulo.", "Ano da defesa.", "Tipo de documento (Grau e Área) – Vinculação acadêmica, Cidade, Ano da defesa.")
    # Tese de doutorado
} else if (params$referencias == "amaral15") {
    p("SOBRENOME, Nome. ", strong("Título do trabalho", .noWS="outside"), ": subtítulo.", "Ano da defesa.", "Tipo de documento (Grau e Área) – Vinculação acadêmica, Cidade, Ano da defesa.")
    # Livro publicado por editores
} else if (params$referencias == "CitekeyProceedings") {
    p("Editor, E. E.; Editor, F. F. (ed./coord./org.). ", strong("Título do livro", .noWS="outside"), ". N. ed. [não indicar 1ª edição]", "Cidade: Nome da editora, ano.")
    # Trabalho não publicado
} else if (params$referencias == "CitekeyUnpublished") {
    p(h4("Não publicados ou em preparação:"), 
      p("AUTOR, A. A.; AUTOR, B. B.; AUTOR, C. C. ", strong("Título do trabalho", .noWS="outside"), ". Fase em que o documento se encontra (No prelo/ Em fase de elaboração/ Não publicado/ Em fase de pré-publicação/ Submetido à publicação)."),
      h4("Aceitos para publicação:"),
      p("AUTOR, A. A.; AUTOR, B. B.; AUTOR, C. C. Título do trabalho. ", strong("Título do periódico", .noWS="outside"), ", Local de publicação (cidade), n. X, data. No prelo.")
      )
    # Blog, revista ou jornal online
} else if (params$referencias == "blogpost") {
    p("AUTOR, A. A. Título do artigo. ", strong("Título do jornal/página", .noWS="outside"), ", Local de publicação (cidade), numeração do ano e/ou volume,  número [se houver], data de publicação, seção, caderno ou parte do jornal e a paginação correspondente [se houver]. Disponível em: http://xxxxx. Acesso em: Dia mês. Ano.", p("Quando não houver seção, caderno ou parte, a paginação do artigo ou matéria precede a data."))
    # Testes, escalas e inventários
} else if (params$referencias == "testes") {
    p("AUTOR, A. A.; Autor, B. B.", strong("Título do teste."), "https://xxxxx")
}


# ABNT exemplos ----------------------------------------------------------

abntex <- if (params$referencias == "CitekeyArticle") {
    p("BORSBOOM, D. The Attack of the Psychometricians. ", strong("Psychometrika", .noWS="outside"), ", [", em("S. l.", .noWS="outside"), "], v. 71, n. 3, p. 425–440, set. 2006.",
      p("Obs: Utilize a expressão sine loco, abreviada, entre colchetes [", em("s. l.", .noWS="outside"), "], caso não seja possível identificar o local de publicação."))
    # 2 Autores
} else if (params$referencias == "CitekeyArticle2") {
    p("KASHDAN, T. B.; ROTTENBERG, J. Psychological flexibility as a fundamental aspect of health. ", strong("Clinical Psychology Review", .noWS="outside"), ", [", em("S. l.", .noWS="outside"), "],  v. 30, n. 7, p. 865–878, 2010.")
    # 3 autores
} else if  (params$referencias == "CitekeyArticle3") {
    p("KASHDAN, T. B.; ROTTENBERG, J. Psychological flexibility as a fundamental aspect of health. ", strong("Perspectives on Psychological Science", .noWS="outside"), ", Washington, v. 30, n. 7, p. 865–878, 2010.")
    # 4+ autores
} else if (params$referencias == "CitekeyArticle4") {
    p("BLANKEN, T. F.", em("et al."), "Network Outcome Analysis Identifies Difficulty Initiating Sleep as a Primary Target for Prevention of Depression: A 6-Year Prospective Study. ", strong("Sleep", .noWS="outside"),  ", Rochester, MN, v. 43, n. 5, p. 1–6, 2020.")
    # 7+
} else if (params$referencias == "CitekeyArticle7") {
    p("BAGLIONI, C.", em("et al."), "Insomnia as a Predictor of Depression: A Meta-Analytic Evaluation of Longitudinal Epidemiological Studies. ", strong("Journal of Affective Disorders", .noWS="outside"),  ", [", em("S. l.", .noWS="outside"), "],  v. 135, n. 1, p. 10–19, 2011.")
    # 21+ autores
} else if (params$referencias == "CitekeyArticle21") {
    p("PAGE, M. J.", em("et al."), "The PRISMA 2020 statement: an updated guideline for reporting systematic reviews. ", strong("BMJ", .noWS="outside"),  ", London, v. 372, 2021.")
    # Autor institucional
} else if (params$referencias == "CitekeyGroupBook") {
    p("AMERICAN PSYCHIATRIC ASSOCIATION. ", strong("Manual Diagnóstico e Estatístico de Transtornos Mentais", .noWS="outside"), ". 5. ed. Porto Alegre: Artmed, 2014.")
    # Livro
} else if (params$referencias == "CitekeyBook") {
    p("Susskind, L., & Hrabovsky, G. (2014). ", strong("Classical mechanics: the theoretical minimum", .noWS="outside"), ". New York, NY: Penguin Random House, 2014")
    # Capítulo de livro
} else if (params$referencias == "CitekeyInbook") {
    p("BALSAM, K. F. et al. Affirmative cognitive behavior therapy with sexual and gender minority people. ", em("In", .noWS="outside"), ":", "IWAMASA, G. Y.; HAYS, P. A. (ed.). " , strong("Culturally responsive cognitive behavior therapy: Practice and supervision", .noWS="outside"), ". 2. ed.", "Washington, DC: American Psychological Association, 2006. p. 7–13. ISBN 1433830167.")
    # Trabalho apresentado em congresso
} else if (params$referencias == "CitekeyInproceedings") {
    p("PEARSON, J. Fat talk and its effects on state-based body image in women. ", em("In", .noWS="outside"), " AUSTRALIAN PSYCHOLOGICAL SOCIETY CONGRESS. 6. 2018, Sydney, NSW. ", strong("Proceedings of the 6th Nordic Conf. on Human-Computer Interaction", .noWS="outside"), ". Sydney, NSW: Australian Psychological Society, 2018. p. 27–30. http://bit.ly/2XGSThP")
    # Dissertação de mestrado
} else if (params$referencias == "CitekeyMastersthesis") {
    p("RODRIGUES, Ana Lúcia Aquilas. ", strong("Impacto de um programa de exercícios no local de trabalho sobre o nível de atividade física e o estágio de prontidão para a mudança de comportamento", .noWS="outside"), ".", "2009.", "Dissertação (Mestrado em Fisiopatologia Experimental) – Faculdade de Medicina, Universidade de São Paulo, São Paulo, 2009. https://www.teses.usp.br/teses/disponiveis/5/5160/tde-24092009-161713/publico/AnaLuciaAquilasRodrigues.pdf")
    # Tese de doutorado
} else if (params$referencias == "amaral15") {
    p("AMARAL, Luana Lopes. ", strong("A alternância transitivo-intransitiva no português brasileiro", .noWS="outside"), ".", "2015.", "Tese (Doutorado em Linguística) – Universidade Federal de Minas Gerais, Belo Horizonte, 2015. http://hdl.handle.net/1843/MGSS-9VNMNV")
    # Livro publicado por editores
} else if (params$referencias == "CitekeyProceedings") {
    p("DAMÁSIO, B. F.; BORSA, J. C. (ed.). ", strong("Manual de desenvolvimento de instrumentos psicológicos", .noWS="outside"), ". São Paulo: Vetor, 2018.")
    # Trabalho não publicado
} else if (params$referencias == "CitekeyUnpublished") {
    p("YOO, J. ", em("et al."), strong(" Linking positive affect to blood lipids", .noWS="outside"), ": A cultural perspective.", "2016. Não publicado.")
    # Blog, revista ou jornal online
} else if (params$referencias == "blogpost") {
    p("KHAN, I. Why Animal Crossing Is the Game for the Coronavirus Moment. ", strong("The New York Times", .noWS="outside"), ". Disponível em: https://www.nytimes.com/2020/04/07/arts/animal-crossing-covid-coronavirus-popularity-millennials.html. Acesso em: 07 mar. 2022.")
    # Testes, escalas e inventários
} else if (params$referencias == "testes") {
    p("Project Implicit. (n.d.).", em("Gender–Science IAT."), "https://implicit.harvard.edu/implicit/takeatest.html")
}
```

```{r vancouver}
# Vancouver formato ------------------------------------------------------------

# Artigo de periódico
vancouvernorms <- if (params$referencias == "CitekeyArticle") {
    p("Autor AA. Título do artigo.", em("Título do periódico abreviado.") ,"ano; volume(número):páginas inicial–final do artigo. doi:10.xxxxxx.")
} else if (params$referencias == "CitekeyArticle2") {
    p("Autor AA, Autor BB. Título do artigo.", em("Título do periódico abreviado.") ,"ano; volume(número):páginas inicial–final do artigo. doi:10.xxxxxx.")
} else if (params$referencias == "CitekeyArticle3") {
    p("Autor AA, Autor BB, Autor CC., Título do artigo.", em("Título do periódico abreviado.") ,"ano; volume(número):páginas inicial–final do artigo. doi:10.xxxxxx.")
} else if (params$referencias == "CitekeyArticle4") {
    p("Autor AA, Autor BB, Autor CC, Autor DD. Título do artigo.", em("Título do periódico abreviado.") ,"ano; volume(número):páginas inicial–final do artigo. doi:10.xxxxxx.")
} else if (params$referencias == "CitekeyArticle7") {
    p("Autor AA, Autor BB, Autor CC, et al. Título do artigo.", em("Título do periódico abreviado.") ,"ano; volume(número):páginas inicial–final do artigo. doi:10.xxxxxx.")
    # 21+ Autores
} else if (params$referencias == "CitekeyArticle21") {
    p("Autor AA, Autor BB, Autor CC, et al. Título do artigo.", em("Título do periódico abreviado.") ,"ano; volume(número):páginas inicial–final do artigo. doi:10.xxxxxx.") 
    # Autor institucional
} else if (params$referencias == "CitekeyGroupBook") {
    p("Nome do grupo. ", em("Título do livro: subtítulo.") ,"Nnd/th ed. [não indicar 1ª edição] Editora; ano. Accessed Mês DD, YYYY. URL [se houver]") 
    # Livro
} else if (params$referencias == "CitekeyBook") {
    p("Autor AA, Autor BB. ", em("Título do livro: subtítulo.") ,"Nnd/th ed. [não indicar 1ª edição] Editora; ano. Acessado Mês DD, YYYY. URL [para e-books online]") 
    # Capítulo de livro
} else if (params$referencias == "CitekeyInbook") {
    p("Autor AA, Autor BB. Título do capítulo. In Editor EE, Editor FF, Editor GG, eds.", em("Título do livro: subtítulo.") ,"Nnd ed. [não indicar 1ª edição] Editora; ano:páginas inicial–final.")
    # Trabalho apresentado em congresso
} else if (params$referencias == "CitekeyInproceedings") {
    p("Autor AA, Autor BB. Título do trabalho. Tipo de apresentação presented at: Nome do congresso; Mês dia inicial–final, Ano; Cidade, Sigla do Estado. Acessado Mês DD, YYYY. URL [para trabalhos online]")
    # Dissertação de mestrado
} else if (params$referencias == "CitekeyMastersthesis") {
    p("Autor AA. ", em("Título da dissertação: subtítulo.") ,"Master’s thesis. Nome da Universidade; Ano. Accessed Mês DD, YYYY. URL [para dissertações online]") 
    # Tese de doutorado
} else if (params$referencias == "amaral15") {
    p("Autor AA. ", em("Título da tese: subtítulo.") ,"Dissertation. Nome da Universidade; Ano. Accessed Mês DD, YYYY. URL [para dissertações online]")
    # Livro publicado por editores
} else if (params$referencias == "CitekeyProceedings") {
    p("Editor EE, Editor FF, eds. ", em("Título do livro: subtítulo.") ,"Nnd/th ed. [apenas edição maior do que a 1ª] Editora; ano. Acessado Mês DD, YYYY. URL [para e-books online]")
    # Trabalho não publicado
} else if (params$referencias == "CitekeyUnpublished") {
    p(h4("Aceito para publicação mas não publicado:"), 
      "Artigos das revistas JAMA Network não incluem estes materiais como referências formais, em especial artigos de periódicos que ainda não foram publicados. Para livros, pode ser utilizada o seguinte modelo:",
      p("Autor AA. ", em("Título do livro: subtítulo.") ,"Editora. Forthcoming Ano."),
      h4("Material submetido para publicação mas ainda não aceito:"),
      "Não devem ser incluídos na lista de referências. Deve ser mencionada no texto como unpublished data:",
      br(),
      "These findings have recently been corroborated (H. E. Marman, MD, unpublished data, January 2015)."
      )
    # Blog, revista ou jornal online
} else if (params$referencias == "blogpost") {
    p("Autor AA. Título do item citado ou nome da organização caso não haja um título. Nome do website. Mês DD, YYYY. Updated Mês DD, YYYY. Accessed Mês DD, YYYY. http://xxxxx")
    # Testes, escalas e inventários
} else if (params$referencias == "testes") {
    p("Autor, A. A. & Autor, B. B.", "(ano).", em("Título do teste."), "https://xxxxx")
}


# Vancouver exemplos ----------------------------------------------------------

vancouverex <- if (params$referencias == "CitekeyArticle") {
    p("(1) Borsboom D. The Attack of the Psychometricians.", em("Psychometrika.") ,"2006; 71(3):425–440. doi:10.1007/s11336-006-1447-6")
} else if (params$referencias == "CitekeyArticle2") {
    p("(1) Kashdan TB, Rottenberg J. Psychological flexibility as a fundamental aspect of health.", em("Clinical Psychology Review.") ,"2010;30(7):865–878. doi:10.1016/j.cpr.2010.03.001")
} else if (params$referencias == "CitekeyArticle3") {
    p("(1) Wijsen LD, Borsboom D, Alexandrova A. Values in Psychometrics.", em("Perspectives on Psychological Science.") ,"2022;17(3):788–804. doi:10.1177/17456916211014183")
} else if (params$referencias == "CitekeyArticle4") {
    p("(1) Blanken TF, Borsboom D, Penninx BW, van Someren EJ. Network Outcome Analysis Identifies Difficulty Initiating Sleep as a Primary Target for Prevention of Depression: A 6-Year Prospective Study.", em("Sleep.") ,"2020;43(5):1–6. doi:10.1093/sleep/zsz288")
} else if (params$referencias == "CitekeyArticle7") {
    p("(1) Baglioni C, Battagliese G, Feige B, et al. Insomnia as a Predictor of Depression: A Meta-Analytic Evaluation of Longitudinal Epidemiological Studies.", em("Journal of Affective Disorders.") ,"2011;135(1):10–9. doi:10.1016/j.jad.2011.01.011")
    # 21+ Autores
} else if (params$referencias == "CitekeyArticle21") {
    p("(1) Page MJ, McKenzie JE, Bossuyt PM, et al. The PRISMA 2020 statement: an updated guideline for reporting systematic reviews.", em("BMJ.") ,"2021;372:n71. doi:10.1136/bmj.n71") 
    # Autor institucional
} else if (params$referencias == "CitekeyGroupBook") {
    p("(1) American Psychiatric Association. ", em("Manual Diagnóstico e Estatístico de Transtornos Mentais.") ,"5th ed. Artmed; 2014.") 
    # Livro
} else if (params$referencias == "CitekeyBook") {
    p("(1) Susskind L, Hrabovsky G. ", em("Classical mechanics: the theoretical minimum.") ,"Penguin Random House; 2014.") 
    # Capítulo de livro
} else if (params$referencias == "CitekeyInbook") {
    p("(1) Balsam, KF, Martell CR, Jones KP, Safren SA. Affirmative cognitive behavior therapy with sexual and gender minority people. In Iwamasa GY, Hays PA, eds.", em("Culturally responsive cognitive behavior therapy: Practice and supervision.") ,"2nd ed. American Psychological Association; 2019:7–13.")
    # Trabalho apresentado em congresso
} else if (params$referencias == "CitekeyInproceedings") {
    p("(1) Pearson J. Fat talk and its effects on state-based body image in women. Poster presented at: Australian Psychological Society Congress; September 27–30, 2018; Sidney, NSW. Acessed March 07, 2022. http://bit.ly/2XGSThP")
    # Dissertação de mestrado
} else if (params$referencias == "CitekeyMastersthesis") {
    p("(1) Rodrigues ALA. ", em("Impacto de um programa de exercícios no local de trabalho sobre o nível de atividade física e o estágio de prontidão para a mudança de comportamento.") ,"Master’s thesis. Faculdade de Medicina, Universidade de São Paulo; 2009. Acessed March 07, 2022. https://www.teses.usp.br/teses/disponiveis/5/5160/tde-24092009-161713/publico/AnaLuciaAquilasRodrigues.pdf") 
    # Tese de doutorado
} else if (params$referencias == "amaral15") {
    p("(1) Amaral LL. ", em("A alternância transitivo-intransitiva no português brasileiro.") ,"Dissertation. Universidade Federal de Minas Gerais; 2015. Acessed March 07, 2022. http://hdl.handle.net/1843/MGSS-9VNMNV")
    # Livro publicado por editores
} else if (params$referencias == "CitekeyProceedings") {
    p("(1) Damásio BF, Borsa JC, eds.", em("Manual de desenvolvimento de instrumentos psicológicos.") ,"Vetor; 2018.")
    # Trabalho não publicado
} else if (params$referencias == "CitekeyUnpublished") {
    p("(1) Christiansen SL, Iverson C, Flanagin A, et al.", em("AMA Manual of Style: A Guide for Authors and Editors.") ,"11th ed. Oxford University Press. Forthcoming 2019.")
    # Blog, revista ou jornal online
} else if (params$referencias == "blogpost") {
    p("(1) Khan I. Why Animal Crossing Is the Game for the Coronavirus Moment. The New York Times. 2020. February 17, 2020. Accessed March 07, 2022. https://www.nytimes.com/2020/04/07/arts/animal-crossing-covid-coronavirus-popularity-millennials.html")
    # Testes, escalas e inventários
} else if (params$referencias == "testes") {
    p("Autor, A. A. & Autor, B. B.", "(ano).", em("Título do teste."), "https://xxxxx")
}
```


## Formato


```{r format}


if (params$norma == "apa7.csl") {
    apa7norms
} else if (params$norma == "planeta-zotero-abnt.csl"){
    abntnorms
} else if (params$norma == "vancouver.csl") {
    vancouvernorms
}

```

## Exemplo

```{r examples}

if (params$norma == "apa7.csl") {
    apa7ex
} else if (params$norma == "planeta-zotero-abnt.csl"){
    abntex
} else if (params$norma == "vancouver.csl") {
    vancouverex
}

```

<hr width="100%; opacity="0.2" />

**Citação entre parêntesis**: [@`r params$referencias`].

**Citação narrativa**: @`r params$referencias`.